#! /bin/sh
# Autostart
Xfce4-panel -d &

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX
xsetroot -cursor_name left_ptr &

bspc config top_padding          28
bspc config bottom_padding       5
bspc config left_padding         0
bspc config right_padding         0
bspc config border_width         3
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config focused_border_color	      "#ffb86c"
bspc config active_border_color	          "#50fa7b"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"



bpsc rule -a Xfce4-panel state=floating border=off
bspc rule -a Xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
sleep 5 && xprop -name "Whisker Menu"
